from RaphaelSomaDIT import rex
rex.studentInfo(email='arfajamohamed56@gmail.com', password='@Dit123456')
print(rex.name)
# print(rex.NTA_level)
# print(rex.nationality)
# print(rex.overall_status)
# print(rex.martial_status)
# print(rex.regno)
# result = rex.result(email='arfajamohamed56@gmail.com', password='@Dit123456')
# print(rex.sem1)
# print(rex.sem2)
# print(rex.GPA_sem1)
# print(rex.GPA_sem1_status)
# # print(rex.studentImage(email='arfajamohamed56@gmail.com', password='@Dit123456'))
# print(rex.photo)